Basic sync-IO stack of longs
sreznick/jstxxl pull request #13
Opened 2021-11-15 18:04 UTC by alex999990009

2021-11-21 23:26 UTC, sreznick requested changes

2021-11-21 23:26 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +    private var currentBlocksOnDisk: Long = 0
Этому полю место в суперклассе

2021-11-21 23:26 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +    private val stackTop = BlockByteSemiDeque(blockSizeLongs * Long.SIZE_BYTES, 2, bufferProvider)
В предке надо определить метод или свойство blockSize и unitSize.
Там же определить:

```stackTop = BlockByteSemiDeque(blockSize() * unitSIze(), 2, bufferProvider)```

2021-11-21 23:26 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +    val size: Long get() = currentBlocksOnDisk * blockSizeLongs + stackTop.sizeLongs
Аналогично. Разница между Int и Long  только в размерах блока и в размерах stackTop.

Их и надо вычислять в подклассе.

2021-11-21 23:26 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +        if (stackTop.sizeLongs == 0) loadBlockFromDisk()
0 для всех типов будет нулем.
Имеет смысл завести  общий ```stackTop.empty```

После этого можно вынести строки 26-27 в отдельные общий метод

2021-11-21 23:26 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +    }
Ничем не отличается от Int

2021-11-21 23:26 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +        storage.seek(--currentBlocksOnDisk * blockSizeLongs * Long.SIZE_BYTES)
Размер блока, по идее, общий для Int/Long.

Здесь должно быть что-то типа storage.seek(--currentBlocksOnDisk * BLOCK_SIZE)

где BLOCK_SIZE - или константа, или что-то, устанавливающееся раз и навсегда.

2021-11-28 19:50 UTC, alex999990009 commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +        storage.seek(--currentBlocksOnDisk * blockSizeLongs * Long.SIZE_BYTES)
Если я правильно понимаю, то, что тогда нам не нужно будет свойство `blockSize`, а нужно ли нам это?

2021-12-03 23:27 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +        storage.seek(--currentBlocksOnDisk * blockSizeLongs * Long.SIZE_BYTES)
Нам нужен какой-то один размер - либо размер в байтах, либо размер в единицах данного типа.
А другой - считать при необходимости.

Я больше за то, чтобы определять BLOCK_SIZE как размер в байтах, а размеры в других единицах - считать делением на размер этих единиц.

2021-12-10 18:50 UTC, alex999990009 commented on src/main/kotlin/com/github/sreznick/jstxxl/stack/LongStackBasic.kt
> +        storage.seek(--currentBlocksOnDisk * blockSizeLongs * Long.SIZE_BYTES)
Исправил

2021-12-11 21:47 UTC, merged