Basic Btree
sreznick/jstxxl pull request #19
Opened 2022-01-11 19:36 UTC by alex999990009

2022-01-12 19:44 UTC, sreznick requested changes

2022-01-12 19:44 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/btree/AbstractBTree.kt
> +        val storage = RandomAccessFileSyncStorage(RandomAccessFile(File(fileName + number), "rw"))
Файлы надо в какой-то момент зарывать.
 Если этого не делать, дескприпторы кончатся.
 
 А еще лучше - открывать файл один раз при создании b-дерева.
И заквывать в методе close.
Тогда файл будет залочен на время работы с b-деревом и его никто не испортит.

2022-01-12 19:44 UTC, sreznick commented on src/main/kotlin/com/github/sreznick/jstxxl/btree/AbstractBTree.kt
> +            for (j in 0 until curNode.numberOfEntries) {
Искать внутри узла лучше бинпоиском

2022-01-14 06:57 UTC, alex999990009 commented on src/main/kotlin/com/github/sreznick/jstxxl/btree/AbstractBTree.kt
> +        val storage = RandomAccessFileSyncStorage(RandomAccessFile(File(fileName + number), "rw"))
Не знаю, сколько дополнительных файлов создам, поэтому использую первый вариант

2022-01-16 22:28 UTC, merged